/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JPanel;

/**
 *
 * @author Thiago
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form mainView
     */
    public MainView() {
        initComponents();
        this.setLocationRelativeTo(this.getParent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        decoratorsPanel = new javax.swing.JPanel();
        Titulo = new javax.swing.JCheckBox();
        legenda = new javax.swing.JCheckBox();
        eixos = new javax.swing.JCheckBox();
        rotulosProporcional = new javax.swing.JCheckBox();
        rotulosTotal = new javax.swing.JCheckBox();
        corBarrasGrupo = new javax.swing.JCheckBox();
        grade = new javax.swing.JCheckBox();
        comboBoxTipoBarra = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnRestaurarPadrao = new javax.swing.JButton();
        btnDesfazer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        decoratorsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elementos Gráficos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        decoratorsPanel.setPreferredSize(new java.awt.Dimension(250, 450));

        Titulo.setText("Título");

        legenda.setText("Legenda");

        eixos.setText("Título dos eixos");

        rotulosProporcional.setText("Rótulo de Dados (%)");

        rotulosTotal.setText("Rótulo de Dados - Valor");

        corBarrasGrupo.setText("Cor das Barras - Por grupo");

        grade.setText("Grade");

        comboBoxTipoBarra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barras Verticais", "Barras Horizontais" }));

        jLabel1.setText("Gráficos Padrão:");

        btnRestaurarPadrao.setText("Restaurar Padrão");

        btnDesfazer.setText("Desfazer");

        javax.swing.GroupLayout decoratorsPanelLayout = new javax.swing.GroupLayout(decoratorsPanel);
        decoratorsPanel.setLayout(decoratorsPanelLayout);
        decoratorsPanelLayout.setHorizontalGroup(
            decoratorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decoratorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(decoratorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(decoratorsPanelLayout.createSequentialGroup()
                        .addGroup(decoratorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Titulo)
                            .addComponent(legenda)
                            .addComponent(eixos)
                            .addComponent(rotulosProporcional)
                            .addComponent(rotulosTotal)
                            .addComponent(corBarrasGrupo)
                            .addComponent(grade))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(decoratorsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17)
                        .addComponent(comboBoxTipoBarra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(decoratorsPanelLayout.createSequentialGroup()
                        .addComponent(btnRestaurarPadrao, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDesfazer, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))))
        );
        decoratorsPanelLayout.setVerticalGroup(
            decoratorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decoratorsPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(legenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eixos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rotulosProporcional)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rotulosTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(corBarrasGrupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(decoratorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxTipoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(decoratorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestaurarPadrao)
                    .addComponent(btnDesfazer))
                .addContainerGap())
        );

        getContentPane().add(decoratorsPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Titulo;
    private javax.swing.JButton btnDesfazer;
    private javax.swing.JButton btnRestaurarPadrao;
    private javax.swing.JComboBox<String> comboBoxTipoBarra;
    private javax.swing.JCheckBox corBarrasGrupo;
    private javax.swing.JPanel decoratorsPanel;
    private javax.swing.JCheckBox eixos;
    private javax.swing.JCheckBox grade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox legenda;
    private javax.swing.JCheckBox rotulosProporcional;
    private javax.swing.JCheckBox rotulosTotal;
    // End of variables declaration//GEN-END:variables

    public JCheckBox getTitulo() {
        return Titulo;
    }


    public JCheckBox getCorBarrasGrupo() {
        return corBarrasGrupo;
    }

    public JPanel getDecoratorsPanel() {
        return decoratorsPanel;
    }

    public JCheckBox getEixos() {
        return eixos;
    }

    public JCheckBox getGrade() {
        return grade;
    }
    

    public JCheckBox getLegenda() {
        return legenda;
    }

    public JCheckBox getRotulosProporcional() {
        return rotulosProporcional;
    }

    public JCheckBox getRotulosTotal() {
        return rotulosTotal;
    }

    public JComboBox<String> getComboBoxTipoBarra() {
        return comboBoxTipoBarra;
    }

    public JButton getBtnDesfazer() {
        return btnDesfazer;
    }

    public JButton getBtnRestaurarPadrao() {
        return btnRestaurarPadrao;
    }
    
}
